### ISSUE TITLE
Yayın oluşturma (controller)

### ISSUE THREAD

**Issue by Aysedalaleh** [Aysedalaleh/sirketOtomasyonu#19]
Şirket Otomasyonu projesinde "Yayın oluşturma" işlevi, kullanıcıların projede yeni bir yayın veya duyuru oluşturabilmesini sağlayan bir kontrolcü (controller) işlemidir.

**Comment by SalihDer** [comment]
Bu işlem, kullanıcının girdiği bilgileri alarak yeni bir yayın kaydının oluşturulmasını sağlar.
