### ISSUE TITLE
Yayın düzeltme (view)

### ISSUE THREAD

**Issue by Aysedalaleh** [Aysedalaleh/sirketOtomasyonu#20]
Şirket Otomasyonu projesinde "Yayın düzeltme" işlevi, kullanıcıların projede mevcut bir yayını düzenleyebilmelerini sağlayan bir görünüm (view) içerir. Bu görünüm, kullanıcının mevcut yayının başlık, içerik, tarih vb.

**Comment by SalihDer** [comment]
bilgilerini düzenleyerek değişiklikleri kaydetmesini sağlar.
