### ISSUE TITLE
yayın düzeltme (controller)

### ISSUE THREAD

**Issue by Aysedalaleh** [Aysedalaleh/sirketOtomasyonu#21]
Şirket Otomasyonu projesinde "Yayın düzeltme" işlevi, kullanıcıların projedeki mevcut bir yayını düzenleyebilmelerini sağlayan bir kontrolcü (controller) işlemidir.

**Comment by SalihDer** [comment]
Bu işlem, kullanıcının girdiği bilgileri alarak mevcut yayın kaydının güncellenmesini sağlar.
