### ISSUE TITLE
yayın silme (contoller)

### ISSUE THREAD

**Issue by Aysedalaleh** [Aysedalaleh/sirketOtomasyonu#23]
Şirket otomasyonu projesinde "yayın silme (controller)" genellikle kullanıcılara belirli bir yayını veya içeriği silme işlemi için gereken iş mantığını ve süreci yöneten bir bileşeni ifade eder.

**Comment by SalihDer** [comment]
Bu bileşen, projenin bir parçası olan yayınların veya içeriklerin veritabanından silinmesini sağlar.
