### ISSUE TITLE
ana kategori oluşturma (view)

### ISSUE THREAD

**Issue by Aysedalaleh** [Aysedalaleh/sirketOtomasyonu#24]
Şirket otomasyonu projesinde "ana kategori oluşturma (view)" genellikle kullanıcıların yeni ana kategorileri oluşturmasına olanak tanıyan bir arayüzü ifade eder.

**Comment by SalihDer** [comment]
Bu görünüm, kullanıcılara yeni ana kategori bilgilerini girmeleri ve kaydetmeleri için bir form veya kullanıcı arayüzü sağlar.
