### ISSUE TITLE
ana kategori oluşturma (conroller)

### ISSUE THREAD

**Issue by Aysedalaleh** [Aysedalaleh/sirketOtomasyonu#25]
"Ana kategori oluşturma (controller)" bileşeni, şirket otomasyonu projesinde kullanıcıların yeni ana kategorileri sisteme kaydetme işlemini yöneten bir bileşeni ifade eder.

**Comment by SalihDer** [comment]
projenin bir parçası olan ana kategorilerin veritabanına kaydedilmesini sağlar.
